name: selaty
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  animated_splash_screen: ^1.3.0
  build_runner: ^2.4.12
  buttons_tabbar: ^1.3.13
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  firebase_core: ^3.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.1
  flutter_native_splash: ^2.3.5
  flutter_screenutil: ^5.7.0
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  geolocator: ^13.0.1
  get_it: ^7.6.4
  image_picker: ^1.1.2
  injectable: ^2.4.4
  injectable_generator: ^2.6.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  lottie: ^3.1.3
  page_transition: ^2.1.0
  pretty_dio_logger: ^1.3.1
  responsive_navigation_bar: ^5.0.2
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
    - assets/lottie/

flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: assets.dart
  field_prefix: resource

flutter_intl:
  enabled: true
